name: "Build and deploy"

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    concurrency:
      group: deployment
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/flathub/linux-store-frontend:${{ github.sha }}
            ghcr.io/flathub/linux-store-frontend:latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
